### ISSUE TITLE
Gemspec requires wrong gem name

### ISSUE THREAD

**Issue by natikgadzhi** [markbates/delayed_job_extras#1]
Hi,

This code: 

<pre><code>
 if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3
 
    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<split_logger>, [">= 0"])
    else
      s.add_dependency(%q<split_logger>, [">= 0"])
    end
  else
    s.add_dependency(%q<split_logger>, [">= 0"])
  end
</code></pre>

requires split_logger gem instead of markbates-split_logger. It affects only systems without gihub gem source settings. 

I've forked your project and pushed the changes. You'll find pull request in you inbox %)

**Comment by natikgadzhi** [comment]
Ouch, the code i've shown looks corrupted by the github textile parser.

**Comment by markbates** [comment]
Thanks. I've updated it and pushed out 0.12.1 with the changes. Thanks a lot.

**Comment by natikgadzhi** [comment]
You're welcome.
